### ISSUE TITLE
Add: Roz Duffy & Jennifer Brook Workshop

### ISSUE THREAD

**Issue by kidfribble** [dockyard/uxeast#50]
**Prototyping in the Woods: Solving Real Problems with Natural, Wearable Technology**

In this wild, outdoor hands-on workshop, we’ll explore the nuances of solving human problems with open minds and bare hands. We’ll practice our research skills with interviewing, brainstorming in nature, and prototyping with found materials. We’ll utilize the outdoors as both the inspiration and source of our explorations while testing new ideas, tools, and approaches we can bring back into our own practice and add to our UX toolkit.

**Roz Duffy** @rozduffy
![tajw9oefqxk6srjh5dyhmcris0nhppg4ljprrug5-be](https://cloud.githubusercontent.com/assets/241320/8295735/9bd55394-1915-11e5-965e-56dd6d11d39d.jpg)
Roz Duffy is a design strategist, researcher & facilitator obsessed with creating delightful experiences for humans. She is a Senior Strategist at Fastspot [http://fastspot.com] where she digs deep into the discovery process of projects for higher ed and cultural institutions. She loves lattes, learning new things, and the creative process.

**Jennifer Brook** @jenniferbrook
![7usalxi5t0klx3vmhfvc8x0sjvixx7igi-jqwgxknwc](https://cloud.githubusercontent.com/assets/241320/8295743/af0af932-1915-11e5-9426-2f67bfc47b66.jpg)
Jennifer Brook is an design researcher who helps product teams do great things. She has an independent design practice in New York and teaches in SVA's MFA of Interaction Design. Her favorite tools are magic wands and time machines.

**Comment by walshtim** [comment]
Take a look at this issue for all speaker info: https://github.com/dockyard/uxeast/issues/54
