### ISSUE TITLE
Last minute speaker update

### ISSUE THREAD

**Issue by rgbcolor** [dockyard/uxeast#77]
Pending OK from speaker.
Changes are shown below. If not listed, the scheduled items remain as they were.
---------

SATURDAY

7:00–8:00 pm
*Talk title TBA*
C. Todd Lombardo

SUNDAY

10:00–10:30 am 
Standup

10:30–12:00 pm 
Breaking the Rules like a Pro
Jackson Wilkinson

5:00–6:30 pm
Personal Project time

MONDAY

11:00–12:00 pm
Stop guessing colors!
Maria Matveeva

**Comment by kidfribble** [comment]
We need to wait for approval of both Jackson and C. Todd. I will officially approve and post photo of C. Todd here when I get it.
